export const bundesnetzagenturHeaders = [
  "Ladeeinrichtungs-ID",
  "Betreiber",
  "Anzeigename (Karte)",
  "Status",
  "Art der Ladeeinrichtung",
  "Anzahl Ladepunkte",
  "Nennleistung Ladeeinrichtung [kW]",
  "Inbetriebnahmedatum",
  "Straße",
  "Hausnummer",
  "Adresszusatz",
  "Postleitzahl",
  "Ort",
  "Kreis/kreisfreie Stadt",
  "Bundesland",
  "Breitengrad",
  "Längengrad",
  "Standortbezeichnung",
  "Informationen zum Parkraum",
  "Bezahlsysteme",
  "Öffnungszeiten",
  "Öffnungszeiten: Wochentage",
  "Öffnungszeiten: Tageszeiten",
  "Steckertypen1",
  "Nennleistung Stecker1",
  "EVSE-ID1",
  "Public Key1",
  "Steckertypen2",
  "Nennleistung Stecker2",
  "EVSE-ID2",
  "Public Key2",
  "Steckertypen3",
  "Nennleistung Stecker3",
  "EVSE-ID3",
  "Public Key3",
  "Steckertypen4",
  "Nennleistung Stecker4",
  "EVSE-ID4",
  "Public Key4",
  "Steckertypen5",
  "Nennleistung Stecker5",
  "EVSE-ID5",
  "Public Key5",
  "Steckertypen6",
  "Nennleistung Stecker6",
  "EVSE-ID6",
  "Public Key6",
] as const;

export type BundesnetzagenturHeader = (typeof bundesnetzagenturHeaders)[number];
export type BundesnetzagenturCSVRecord = Record<BundesnetzagenturHeader, string>;
